pages:
  script:
    - date
  artifacts:
    paths:
      - public

build:java:
  image: fedora:latest
  script:
  - cd java 
  - pwd 
  - dnf upgrade --refresh -yqq 
  - dnf install java-devel -yqq 
  - export JAVA_HOME=$(dirname $(dirname $(readlink $(readlink $(which javac)))))
  - javac -version 
  - java -version 
  - dnf install unzip wget -yqq
  - wget https://downloads.gradle-dn.com/distributions/gradle-6.3-bin.zip
  - unzip gradle-6.3-bin.zip
  - mv gradle-6.3 /usr/local/gradle
  - export PATH=/usr/local/gradle/bin:$PATH
  - gradle --version
  - gradle wrapper --gradle-version 2.13
  - ./gradlew build
  - ./gradlew run
  
